config/routes.rb
Af::Application.routes.draw do

  get "home/index"

  get '/auth/twitter/callback', :to => 'sessions#create', :as => 'callback'
  get '/auth/failure', :to => 'sessions#error', :as => 'failure'
  get '/profile', :to => 'sessions#show', :as => 'show'
  delete '/signout', :to => 'sessions#destroy', :as => 'signout'

  match "/signout" => "sessions#destroy", :as => :signout
  resources :causes do
    member do
      post :vote_up, :vote_down#, :flag
    end
  end
  resources :activities do
    member do
      post :vote_up, :vote_down#, :flag
    end
  end
  resources :users, :only => [:show, :update]
  resources :incentives do
    member do
      put :claim, :validate
      post :vote_up, :vote_down#, :flag
    end
  end

  get "/phillystartup" => "incentives#index"

  root :to => 'home#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  acts_as_voteable
  #make_flaggable
  has_many :incentives

  belongs_to :cause
  belongs_to :submitter, :class_name => 'User'
  validates :name, :presence => true

  def popularity
    plusminus
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def vote_up
    current_user.vote_up Activity.find(params[:id])
    redirect_to :back
  end

  def vote_down
    current_user.vote_down Activity.find(params[:id])
    redirect_to :back
  end

  # def flag
  #   begin
  #     current_user.flag(@activity = Activity.find(params[:id]))
  #     render :nothing => true, :status => 200
  #   rescue
  #     render :nothing => true, :status => 404
  #   end
  # end

  def show
    @activities = Activity.all
    @activity = Activity.find params[:id]
  end

  def new
    @activity = Activity.new
    @causes = Cause.all
  end

  def create
    @activity = Activity.new(params[:activity])
    @activity.submitter = current_user
    if @activity.save
      flash[:notice] = "Thanks for creating a new activity in support of your cause!"
      redirect_to activities_path
    else
      flash[:error] = @activity.errors
      redirect_to new_activity_path :cause_id => @activity.cause_id
    end
  end

  def index
    @activities = Activity.all
  end
end

app/views/activities/_list.html.haml
- current ||= nil
%ul
  - activities.each do |activity|
    %li
      = (activity==current) ? activity.name : link_to(activity.name, activity)

app/views/activities/index.html.haml
.new
  = link_to "Create a new Activity", new_activity_path

-@activities.each do |activity|
  .activity
    = render :partial => "shared/vote", :locals => {:target => activity}
    = link_to activity.name, incentives_path(:activity_id => activity.id)
    .popularity Popularity: #{activity.popularity}
    .clear

app/views/activities/new.html.haml
= semantic_form_for @activity do |f|
  = f.inputs do
    =f.input :cause
    =f.input :name, :as => :string
    =f.input :description
  = f.buttons

app/views/activities/show.html.haml
= render :partial => "activities/list", :locals => { :activities => @activities, :current => @activity }
= render :partial => "incentives/list", :locals => { :incentives => @activity.incentives }