config/routes.rb
Af::Application.routes.draw do

  get "home/index"

  get '/auth/twitter/callback', :to => 'sessions#create', :as => 'callback'
  get '/auth/failure', :to => 'sessions#error', :as => 'failure'
  get '/profile', :to => 'sessions#show', :as => 'show'
  delete '/signout', :to => 'sessions#destroy', :as => 'signout'

  match "/signout" => "sessions#destroy", :as => :signout
  resources :causes do
    member do
      post :vote_up, :vote_down#, :flag
    end
  end
  resources :activities do
    member do
      post :vote_up, :vote_down#, :flag
    end
  end
  resources :users, :only => [:show, :update]
  resources :incentives do
    member do
      put :claim, :validate
      post :vote_up, :vote_down#, :flag
    end
  end

  get "/phillystartup" => "incentives#index"

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diff</title>
  <%= render :partial => 'fonts' %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="logo">
    <a href="/incentives">Diff</a>
    <span class="tagline">Make a difference.  Quickly.</span>
  </div>
  <div class="nav">
    <% if logged_in_user %>
      Welcome, <%= logged_in_user.name %>!
      <%= link_to "Sign Out", signout_path %>
    <% else %>
      Welcome, <%= current_user.name %>!
      <%= link_to "Sign in with Twitter", "/auth/twitter", :class => :button %>
    <% end %>
  </div>
  <div class="menu">
    <%= link_to "Causes", causes_path %>
    <%= link_to "Activities", activities_path %>
    <%= link_to "My Account", user_path(current_user) %>
  </div>
</div>

<% if flash[:warning] or flash[:notice] %>
  <div class="notice">
    <%= flash[:warning] || flash[:notice] %>
  </div>
<% end %>

<div class="content">
  <%= yield %>
<div>

</body>
</html>

app/views/layouts/splash.html.haml
!!!
%html
  %head
    %title Diff
    = render :partial => 'fonts'
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.splash
    = yield